# Generated by Django 5.2 on 2025-05-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bid_amount_alter_luxuryshoe_starting_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='luxuryshoe',
            name='auction_duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes'),
        ),
    ]
