# Generated by Django 5.2 on 2025-05-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_options_luxuryshoe_auction_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luxuryshoe',
            name='auction_duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration of the auction in minutes'),
        ),
    ]
