# Generated by Django 5.2 on 2025-05-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_contactmessage_order_payment_id_order_payment_status_and_more'),
        ('Store', '0005_order_payment_id_order_payment_status_and_more'),
    ]

    operations = [
    ]
