# Generated by Django 5.2 on 2025-05-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_luxuryshoe_auction_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luxuryshoe',
            name='auction_duration',
        ),
        migrations.AlterField(
            model_name='luxuryshoe',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
