# Generated by Django 5.2 on 2025-05-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
